/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedIdRouteImport } from './routes/shared.$id'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIdRoute = SharedIdRouteImport.update({
  id: '/shared/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/result' | '/shared/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/result' | '/shared/$id'
  id: '__root__' | '/' | '/quiz' | '/result' | '/shared/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  ResultRoute: typeof ResultRoute
  SharedIdRoute: typeof SharedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  ResultRoute: ResultRoute,
  SharedIdRoute: SharedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
